using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;

namespace AbilityKit.Editor.GamplayTag
{
    internal static class GameplayTagLibExporter
    {
        private const string OutputPathPrefKey = "AbilityKit.GameplayTags.ExportPath";
        public const string DefaultOutputPath = "Assets/Scripts/Ability/Share/Common/TagSystem/GameplayTagLib.cs";

        public static string GetOutputPath()
        {
            var p = EditorPrefs.GetString(OutputPathPrefKey, DefaultOutputPath);
            return string.IsNullOrWhiteSpace(p) ? DefaultOutputPath : p;
        }

        public static void SetOutputPath(string outputPath)
        {
            if (string.IsNullOrWhiteSpace(outputPath))
            {
                EditorPrefs.SetString(OutputPathPrefKey, DefaultOutputPath);
                return;
            }

            EditorPrefs.SetString(OutputPathPrefKey, outputPath);
        }

        public static void Export(GameplayTagDatabase db, string outputPath = null)
        {
            if (db == null) throw new ArgumentNullException(nameof(db));

            outputPath ??= GetOutputPath();

            var entries = db.Entries ?? Array.Empty<GameplayTagDatabase.Entry>();
            var normalized = new List<string>(entries.Count);
            var commentByName = new Dictionary<string, string>(StringComparer.Ordinal);
            for (int i = 0; i < entries.Count; i++)
            {
                var e = entries[i];
                if (e == null) continue;
                if (GameplayTagValidation.TryNormalize(e.Name, out var n))
                {
                    normalized.Add(n);
                    commentByName[n] = e.Comment ?? string.Empty;
                }
            }

            normalized.Sort(StringComparer.Ordinal);

            var used = new HashSet<string>(StringComparer.Ordinal);
            var nameMap = new Dictionary<string, string>(StringComparer.Ordinal);

            for (int i = 0; i < normalized.Count; i++)
            {
                var t = normalized[i];
                var id = ToIdentifier(t);
                id = EnsureUniqueIdentifier(id, used, t);
                nameMap[t] = id;
            }

            var sb = new StringBuilder(32 * 1024);
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Generated by GameplayTagManagerWindow");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
            sb.AppendLine("namespace AbilityKit.Core.Utilities.TagSystem");
            sb.AppendLine("{");
            sb.AppendLine("    public static class GameplayTagLib");
            sb.AppendLine("    {");
            sb.AppendLine("        public static class Names");
            sb.AppendLine("        {");

            for (int i = 0; i < normalized.Count; i++)
            {
                var t = normalized[i];
                var id = nameMap[t];
                if (commentByName.TryGetValue(t, out var c) && !string.IsNullOrWhiteSpace(c))
                {
                    AppendXmlDocComment(sb, "            ", c);
                }
                sb.Append("            public const string ").Append(id).Append(" = \"").Append(EscapeCSharpString(t)).AppendLine("\";");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static class Tags");
            sb.AppendLine("        {");

            for (int i = 0; i < normalized.Count; i++)
            {
                var name = normalized[i];
                var id = nameMap[name];
                if (commentByName.TryGetValue(name, out var c) && !string.IsNullOrWhiteSpace(c))
                {
                    AppendXmlDocComment(sb, "            ", c);
                }
                sb.Append("            public static readonly GameplayTag ").Append(id).Append(" = GameplayTags.Tag(Names.").Append(id).AppendLine(");");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static bool s_registered;");
            sb.AppendLine();
            sb.AppendLine("        public static void RegisterAll()");
            sb.AppendLine("        {");
            sb.AppendLine("            if (s_registered) return;");
            sb.AppendLine("            s_registered = true;");

            for (int i = 0; i < normalized.Count; i++)
            {
                var id = nameMap[normalized[i]];
                sb.Append("            GameplayTags.Tag(Names.").Append(id).AppendLine(");");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static IReadOnlyList<string> AllNames { get; } = new[]");
            sb.AppendLine("        {");
            for (int i = 0; i < normalized.Count; i++)
            {
                sb.Append("            Names.").Append(nameMap[normalized[i]]).AppendLine(",");
            }
            sb.AppendLine("        };");

            sb.AppendLine();
            sb.AppendLine("        public static IReadOnlyList<GameplayTag> AllTags { get; } = new[]");
            sb.AppendLine("        {");
            for (int i = 0; i < normalized.Count; i++)
            {
                sb.Append("            Tags.").Append(nameMap[normalized[i]]).AppendLine(",");
            }
            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            var dir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(dir)) Directory.CreateDirectory(dir);

            File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
            AssetDatabase.ImportAsset(outputPath, ImportAssetOptions.ForceUpdate);
        }

        private static string ToIdentifier(string tag)
        {
            if (string.IsNullOrEmpty(tag)) return "Empty";

            var sb = new StringBuilder(tag.Length);
            for (int i = 0; i < tag.Length; i++)
            {
                var c = tag[i];
                if (c == '.')
                {
                    sb.Append('_');
                    continue;
                }

                if (char.IsLetterOrDigit(c) || c == '_')
                {
                    sb.Append(c);
                }
                else
                {
                    sb.Append('_');
                }
            }

            var s = sb.ToString();
            if (s.Length == 0) s = "Tag";
            if (char.IsDigit(s[0])) s = "T_" + s;
            return s;
        }

        private static string EnsureUniqueIdentifier(string id, HashSet<string> used, string fullTag)
        {
            if (used.Add(id)) return id;

            unchecked
            {
                uint h = 2166136261u;
                for (int i = 0; i < fullTag.Length; i++)
                {
                    h ^= fullTag[i];
                    h *= 16777619u;
                }

                var candidate = id + "_" + h.ToString("X8");
                if (used.Add(candidate)) return candidate;
            }

            var n = 2;
            while (true)
            {
                var candidate = id + "_" + n;
                if (used.Add(candidate)) return candidate;
                n++;
            }
        }

        private static string EscapeCSharpString(string s)
        {
            if (string.IsNullOrEmpty(s)) return string.Empty;
            var sb = new StringBuilder(s.Length);
            for (int i = 0; i < s.Length; i++)
            {
                var c = s[i];
                switch (c)
                {
                    case '\\':
                        sb.Append("\\\\");
                        break;
                    case '"':
                        sb.Append("\\\"");
                        break;
                    case '\r':
                        sb.Append("\\r");
                        break;
                    case '\n':
                        sb.Append("\\n");
                        break;
                    case '\t':
                        sb.Append("\\t");
                        break;
                    default:
                        sb.Append(c);
                        break;
                }
            }
            return sb.ToString();
        }

        private static void AppendXmlDocComment(StringBuilder sb, string indent, string comment)
        {
            if (sb == null) return;
            if (string.IsNullOrWhiteSpace(comment)) return;

            var lines = comment.Replace("\r\n", "\n").Replace("\r", "\n").Split('\n');

            sb.Append(indent).AppendLine("/// <summary>");
            for (int i = 0; i < lines.Length; i++)
            {
                var line = lines[i] ?? string.Empty;
                sb.Append(indent).Append("///");
                if (line.Length > 0)
                {
                    sb.Append(' ').Append(EscapeXml(line));
                }
                sb.AppendLine();
            }
            sb.Append(indent).AppendLine("/// </summary>");
        }

        private static string EscapeXml(string s)
        {
            if (string.IsNullOrEmpty(s)) return string.Empty;
            return s
                .Replace("&", "&amp;")
                .Replace("<", "&lt;")
                .Replace(">", "&gt;")
                .Replace("\"", "&quot;")
                .Replace("'", "&apos;");
        }
    }
}
