using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Share.SourceGenerator;

namespace AbilityKit.SourceGenerator
{
    /// <summary>
    /// AutoPlanAction 的 Source Generator
    /// 扫描所有继承 AutoPlanAction 的类，自动生成 Module 注册代码
    /// </summary>
    [Generator]
    public class AutoPlanActionGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new SyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            var receiver = context.SyntaxContextReceiver as SyntaxReceiver;
            if (receiver == null) return;

            // 生成注册文件
            var source = GenerateRegistrationCode(receiver.Actions);
            context.AddSource("AutoPlanAction_Registration.g.cs", source);
        }

        private string GenerateRegistrationCode(List<ActionTypeInfo> actions)
        {
            if (actions.Count == 0)
                return "// No AutoPlanAction found";

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using AbilityKit.Ability.World.DI;");
            sb.AppendLine("using AbilityKit.Triggering.Registry;");
            sb.AppendLine("using AbilityKit.Triggering.Runtime;");
            sb.AppendLine("using AbilityKit.Triggering.Runtime.Plan;");
            sb.AppendLine();
            sb.AppendLine("namespace AbilityKit.Triggering.Runtime.Plan");
            sb.AppendLine("{");

            // 生成注册类
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// AutoPlanAction 注册表（自动生成）");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    [System.CodeDom.Compiler.GeneratedCode(\"AutoPlanActionGenerator\", \"1.0\")]");
            sb.AppendLine("    public static class AutoPlanActionRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        private static bool _registered;");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 注册所有 AutoPlanAction");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static void RegisterAll(ActionRegistry actions, IWorldResolver services)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (_registered || actions == null) return;");
            sb.AppendLine("            _registered = true;");
            sb.AppendLine();

            // 按 Order 排序
            actions.Sort((a, b) => a.Order.CompareTo(b.Order));

            foreach (var action in actions)
            {
                sb.AppendLine($"            // 注册 {action.FullName}");
                sb.AppendLine($"            {action.FullName}.Register(actions, services);");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();

            // 为每个 Action 生成 partial class（用于自动注册）
            foreach (var action in actions)
            {
                sb.AppendLine($"namespace {action.Namespace}");
                sb.AppendLine("{");
                sb.AppendLine($"    /// <summary>");
                sb.AppendLine($"    /// 自动生成的注册代码（{action.FullName}）");
                sb.AppendLine($"    /// </summary>");
                sb.AppendLine($"    [System.CodeDom.Compiler.GeneratedCode(\"AutoPlanActionGenerator\", \"1.0\")]");
                sb.AppendLine($"    public partial class {action.Name} : IAutoPlanActionRegistration");
                sb.AppendLine("    {");
                sb.AppendLine($"        private static readonly ActionId __actionId = new ActionId(StableStringId.Get(\"action:{action.ActionId}\"));");
                sb.AppendLine();
                sb.AppendLine($"        public static void Register(ActionRegistry actions, IWorldResolver services)");
                sb.AppendLine("        {");
                sb.AppendLine("            if (actions == null) return;");
                sb.AppendLine($"            var actionId = __actionId;");
                sb.AppendLine();
                sb.AppendLine("            // 注册 Schema");
                sb.AppendLine($"            ActionSchemaRegistry.Register(new {action.Name}Schema(actionId));");
                sb.AppendLine();
                sb.AppendLine("            // 注册所有 Arity");
                sb.AppendLine($"            actions.Register<NamedAction0<object, object, IWorldResolver>>(actionId, __OnExecute0, isDeterministic: true);");
                sb.AppendLine($"            actions.Register<NamedAction1<object, object, IWorldResolver>>(actionId, __OnExecute1, isDeterministic: true);");
                sb.AppendLine($"            actions.Register<NamedAction2<object, object, IWorldResolver>>(actionId, __OnExecute2, isDeterministic: true);");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine($"        private static void __OnExecute0(object triggerArgs, object actionArgs, ExecCtx<IWorldResolver> ctx) => __Execute(triggerArgs, null, ctx);");
                sb.AppendLine($"        private static void __OnExecute1(object triggerArgs, object actionArgs, ExecCtx<IWorldResolver> ctx) => __Execute(triggerArgs, __ToNamedArgs(actionArgs), ctx);");
                sb.AppendLine($"        private static void __OnExecute2(object triggerArgs, object actionArgs, ExecCtx<IWorldResolver> ctx) => __Execute(triggerArgs, __ToNamedArgs(actionArgs), ctx);");
                sb.AppendLine();
                sb.AppendLine("        private static void __Execute(object triggerArgs, Dictionary<string, ActionArgValue> namedArgs, ExecCtx<IWorldResolver> ctx)");
                sb.AppendLine("        {");
                sb.AppendLine("            if (ctx.Context == null) return;");
                sb.AppendLine("            try");
                sb.AppendLine("            {");
                sb.AppendLine($"                var instance = new {action.Name}();");
                sb.AppendLine($"                instance.ParseFrom(namedArgs, ctx);");
                sb.AppendLine($"                instance.Execute(triggerArgs, ctx);");
                sb.AppendLine("            }");
                sb.AppendLine("            catch (Exception ex)");
                sb.AppendLine("            {");
                sb.AppendLine($"                Core.Common.Log.Log.Exception(ex, \"[Plan] {action.Name} execution failed\");");
                sb.AppendLine("            }");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        private static Dictionary<string, ActionArgValue> __ToNamedArgs(object rawArgs)");
                sb.AppendLine("        {");
                sb.AppendLine("            if (rawArgs is NamedArgsDict dict) return dict.InnerDict;");
                sb.AppendLine("            if (rawArgs is Dictionary<string, ActionArgValue> d) return d;");
                sb.AppendLine("            return null;");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine("}");
                sb.AppendLine();

                // 生成 Schema
                sb.AppendLine($"namespace {action.Namespace}");
                sb.AppendLine("{");
                sb.AppendLine($"    /// <summary>");
                sb.AppendLine($"    /// 自动生成的 Schema（{action.Name}）");
                sb.AppendLine($"    /// </summary>");
                sb.AppendLine($"    [System.CodeDom.Compiler.GeneratedCode(\"AutoPlanActionGenerator\", \"1.0\")]");
                sb.AppendLine($"    public sealed class {action.Name}Schema : IActionSchema");
                sb.AppendLine("    {");
                sb.AppendLine($"        private readonly ActionId _actionId;");
                sb.AppendLine($"        public {action.Name}Schema(ActionId actionId) {{ _actionId = actionId; }}");
                sb.AppendLine($"        public ActionId ActionId => _actionId;");
                sb.AppendLine($"        public Type ArgsType => typeof({action.Name});");
                sb.AppendLine();
                sb.AppendLine($"        public object ParseArgs(Dictionary<string, ActionArgValue> namedArgs, object ctx)");
                sb.AppendLine("        {");
                sb.AppendLine($"            var instance = new {action.Name}();");
                sb.AppendLine("            ExecCtx<IWorldResolver> execCtx;");
                sb.AppendLine("            if (ctx is ExecCtx<IWorldResolver> ec) execCtx = ec; else execCtx = default;");
                sb.AppendLine($"            instance.ParseFrom(namedArgs, execCtx);");
                sb.AppendLine($"            return instance;");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine($"        public bool TryValidateArgs(ReadOnlySpan<KeyValuePair<string, ActionArgValue>> args, out string error)");
                sb.AppendLine("        {");
                sb.AppendLine($"            error = null;");
                sb.AppendLine($"            return true;");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine("}");
                sb.AppendLine();
            }

            return sb.ToString();
        }
    }

    internal class SyntaxReceiver : ISyntaxContextReceiver
    {
        public List<ActionTypeInfo> Actions { get; } = new List<ActionTypeInfo>();

        public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
        {
            var node = context.Node;

            // 只处理 Class 声明
            if (node is not ClassDeclarationSyntax classDecl)
                return;

            var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
            if (symbol == null) return;

            // 检查是否继承 AutoPlanAction
            bool inheritsAutoPlanAction = false;
            var baseType = symbol.BaseType;
            while (baseType != null)
            {
                if (baseType.Name == "AutoPlanAction")
                {
                    inheritsAutoPlanAction = true;
                    break;
                }
                baseType = baseType.BaseType;
            }

            if (!inheritsAutoPlanAction)
                return;

            // 获取 ActionId
            string actionId = symbol.Name;
            int order = 0;

            foreach (var member in symbol.GetMembers())
            {
                if (member is IPropertySymbol prop)
                {
                    if (prop.Name == "ActionId" && prop.Type.Name == "String")
                    {
                        // 尝试获取常量值
                        if (prop.DeclaringSyntaxReferences.Length > 0)
                        {
                            var syntax = prop.DeclaringSyntaxReferences[0].GetSyntax();
                            if (syntax is PropertyDeclarationSyntax propDecl)
                            {
                                var expr = propDecl.Expression as LiteralExpressionSyntax;
                                if (expr != null)
                                {
                                    actionId = expr.Token.ValueText;
                                }
                            }
                        }
                    }
                }
            }

            // 获取 Order
            foreach (var member in symbol.GetMembers())
            {
                if (member is IPropertySymbol prop && prop.Name == "Order" && prop.Type.Name == "Int32")
                {
                    if (prop.DeclaringSyntaxReferences.Length > 0)
                    {
                        var syntax = prop.DeclaringSyntaxReferences[0].GetSyntax();
                        if (syntax is PropertyDeclarationSyntax propDecl)
                        {
                            var expr = propDecl.Expression as LiteralExpressionSyntax;
                            if (expr != null)
                            {
                                order = Convert.ToInt32(expr.Token.Value);
                            }
                        }
                    }
                }
            }

            Actions.Add(new ActionTypeInfo
            {
                Name = symbol.Name,
                Namespace = symbol.ContainingNamespace?.ToString() ?? "GlobalNamespace",
                ActionId = actionId,
                Order = order
            });
        }
    }

    internal class ActionTypeInfo
    {
        public string Name { get; set; }
        public string Namespace { get; set; }
        public string ActionId { get; set; }
        public int Order { get; set; }
        public string FullName => string.IsNullOrEmpty(Namespace) || Namespace == "GlobalNamespace"
            ? Name
            : $"{Namespace}.{Name}";
    }
}
