using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Share.SourceGenerator;

namespace AbilityKit.SourceGenerator
{
    /// <summary>
    /// AutoPredicate 的 Source Generator
    /// 扫描所有继承 AutoPredicate 的类，自动生成注册代码
    /// </summary>
    [Generator]
    public class AutoPredicateGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new SyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            var receiver = context.SyntaxContextReceiver as SyntaxReceiver;
            if (receiver == null) return;

            // 生成注册文件
            var source = GenerateRegistrationCode(receiver.Predicates);
            context.AddSource("AutoPredicate_Registration.g.cs", source);
        }

        private string GenerateRegistrationCode(List<PredicateTypeInfo> predicates)
        {
            if (predicates.Count == 0)
                return "// No AutoPredicate found";

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using AbilityKit.Ability.World.DI;");
            sb.AppendLine("using AbilityKit.Triggering.Registry;");
            sb.AppendLine("using AbilityKit.Triggering.Runtime;");
            sb.AppendLine("using AbilityKit.Triggering.Runtime.Behavior.Predicates;");
            sb.AppendLine("using AbilityKit.Triggering.CodeGen;");
            sb.AppendLine("using AbilityKit.Triggering.Runtime.Config.Predicates;");
            sb.AppendLine();
            sb.AppendLine("namespace AbilityKit.Triggering.Runtime.Behavior.Predicates");
            sb.AppendLine("{");

            // 生成注册类
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// AutoPredicate 注册表（自动生成）");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    [System.CodeDom.Compiler.GeneratedCode(\"AutoPredicateGenerator\", \"1.0\")]");
            sb.AppendLine("    public static class AutoPredicateRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        private static bool _registered;");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 注册所有 AutoPredicate");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static void RegisterAll()");
            sb.AppendLine("        {");
            sb.AppendLine("            if (_registered) return;");
            sb.AppendLine("            _registered = true;");
            sb.AppendLine();

            // 按 Order 排序
            predicates.Sort((a, b) => a.Order.CompareTo(b.Order));

            foreach (var predicate in predicates)
            {
                sb.AppendLine($"            // 注册 {predicate.FullName}");
                sb.AppendLine($"            TriggerConditionRegistry.Instance.Register(\"{predicate.PredicateType}\", typeof({predicate.FullName}));");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();

            // 为每个 Predicate 生成 partial class
            foreach (var predicate in predicates)
            {
                sb.AppendLine($"namespace {predicate.Namespace}");
                sb.AppendLine("{");
                sb.AppendLine($"    /// <summary>");
                sb.AppendLine($"    /// 自动生成的注册代码（{predicate.FullName}）");
                sb.AppendLine($"    /// </summary>");
                sb.AppendLine($"    [System.CodeDom.Compiler.GeneratedCode(\"AutoPredicateGenerator\", \"1.0\")]");
                sb.AppendLine($"    public partial class {predicate.Name} : IAutoPredicateRegistration");
                sb.AppendLine("    {");
                sb.AppendLine($"        void IAutoPredicateRegistration.Register()");
                sb.AppendLine("        {");
                sb.AppendLine($"            TriggerConditionRegistry.Instance.Register(\"{predicate.PredicateType}\", typeof({predicate.Name}));");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine("}");
                sb.AppendLine();
            }

            return sb.ToString();
        }
    }

    internal class SyntaxReceiver : ISyntaxContextReceiver
    {
        public List<PredicateTypeInfo> Predicates { get; } = new List<PredicateTypeInfo>();

        public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
        {
            var node = context.Node;

            // 只处理 Class 声明
            if (node is not ClassDeclarationSyntax classDecl)
                return;

            var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
            if (symbol == null) return;

            // 检查是否继承 AutoPredicate
            bool inheritsAutoPredicate = false;
            var baseType = symbol.BaseType;
            while (baseType != null)
            {
                if (baseType.Name == "AutoPredicate")
                {
                    inheritsAutoPredicate = true;
                    break;
                }
                baseType = baseType.BaseType;
            }

            if (!inheritsAutoPredicate)
                return;

            // 获取 PredicateType
            string predicateType = symbol.Name;
            int order = 0;

            foreach (var member in symbol.GetMembers())
            {
                if (member is IPropertySymbol prop)
                {
                    if (prop.Name == "PredicateType" && prop.Type.Name == "String")
                    {
                        if (prop.DeclaringSyntaxReferences.Length > 0)
                        {
                            var syntax = prop.DeclaringSyntaxReferences[0].GetSyntax();
                            if (syntax is PropertyDeclarationSyntax propDecl)
                            {
                                var expr = propDecl.Expression as LiteralExpressionSyntax;
                                if (expr != null)
                                {
                                    predicateType = expr.Token.ValueText;
                                }
                            }
                        }
                    }
                    else if (prop.Name == "Order" && prop.Type.Name == "Int32")
                    {
                        if (prop.DeclaringSyntaxReferences.Length > 0)
                        {
                            var syntax = prop.DeclaringSyntaxReferences[0].GetSyntax();
                            if (syntax is PropertyDeclarationSyntax propDecl)
                            {
                                var expr = propDecl.Expression as LiteralExpressionSyntax;
                                if (expr != null)
                                {
                                    order = Convert.ToInt32(expr.Token.Value);
                                }
                            }
                        }
                    }
                }
            }

            Predicates.Add(new PredicateTypeInfo
            {
                Name = symbol.Name,
                Namespace = symbol.ContainingNamespace?.ToString() ?? "GlobalNamespace",
                PredicateType = predicateType,
                Order = order
            });
        }
    }

    internal class PredicateTypeInfo
    {
        public string Name { get; set; }
        public string Namespace { get; set; }
        public string PredicateType { get; set; }
        public int Order { get; set; }
        public string FullName => string.IsNullOrEmpty(Namespace) || Namespace == "GlobalNamespace"
            ? Name
            : $"{Namespace}.{Name}";
    }
}
