using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using AbilityKit.ProtocolEditor.Schema;
using UnityEditor;
using UnityEngine;

namespace AbilityKit.ProtocolEditor.Generator
{
    public static class ProtocolCodeGenerator
    {
        public static void GenerateCustomBinaryBackendStubs(ProtocolDefinition def, string outputFolder, string @namespace)
        {
            if (!CodecBackendGenerators.TryGet(ProtocolDefinition.CodecBackend.CustomBinary, out var generator))
            {
                Debug.LogError("CustomBinary codec backend generator is not registered.");
                return;
            }

            generator.GenerateImplementationStubs(def, outputFolder, @namespace);
        }

        public static void GenerateSnapshotRoutingGlue(ProtocolDefinition def, string outputFolder, string @namespace)
        {
            if (def == null) throw new ArgumentNullException(nameof(def));
            if (string.IsNullOrWhiteSpace(outputFolder)) throw new ArgumentException("Output folder is required", nameof(outputFolder));
            if (string.IsNullOrWhiteSpace(@namespace)) throw new ArgumentException("Namespace is required", nameof(@namespace));
            if (string.IsNullOrWhiteSpace(def.RegistryId)) throw new ArgumentException("RegistryId is required in ProtocolDefinition", nameof(def));

            Directory.CreateDirectory(outputFolder);

            var registryClassName = $"SnapshotRegistry_{SanitizeIdentifier(def.RegistryId)}";
            var fileName = $"SnapshotRegistry.{SanitizeIdentifier(def.RegistryId)}.g.cs";

            var usedBackends = new HashSet<ProtocolDefinition.CodecBackend>();
            foreach (var msg in def.Messages)
            {
                if (msg == null) continue;
                usedBackends.Add(msg.Backend);
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using AbilityKit.Ability.Host;");
            sb.AppendLine("using AbilityKit.Core.Common.SnapshotRouting;");
            sb.AppendLine();
            sb.AppendLine($"namespace {@namespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    [SnapshotRegistry(\"{EscapeString(def.RegistryId)}\")]" );
            sb.AppendLine($"    internal static class {registryClassName}");
            sb.AppendLine("    {");

            foreach (var msg in def.Messages)
            {
                if (msg == null) continue;
                if (string.IsNullOrWhiteSpace(msg.Name)) continue;
                if (string.IsNullOrWhiteSpace(msg.PayloadTypeName)) continue;

                var methodName = $"{SanitizeIdentifier(msg.Name)}";
                var payloadType = msg.PayloadTypeName.Trim();
                CodecBackendGenerators.TryGet(msg.Backend, out var backendGenerator);
                var backendClassName = GetBackendClassName(def.RegistryId, msg.Backend);

                switch (msg.Channel)
                {
                    case ProtocolDefinition.ChannelKind.SnapshotDecoder:
                        sb.AppendLine($"        [SnapshotDecoder(\"{EscapeString(def.RegistryId)}\", {msg.OpCode}, typeof({payloadType}))]");
                        sb.AppendLine($"        internal static bool Decode_{methodName}(in WorldStateSnapshot snap, out {payloadType} value)");
                        sb.AppendLine("        {");
                        sb.AppendLine("            value = default;");
                        sb.AppendLine("            var handled = false;");
                        if (backendGenerator != null)
                        {
                            backendGenerator.AppendGlueInvocation(sb, def, msg, backendClassName, methodName, payloadType, indent: 8);
                        }
                        sb.AppendLine();
                        sb.AppendLine("            return handled;");
                        sb.AppendLine("        }");
                        sb.AppendLine();
                        break;

                    case ProtocolDefinition.ChannelKind.SnapshotCmdHandler:
                        sb.AppendLine($"        [SnapshotCmdHandler(\"{EscapeString(def.RegistryId)}\", {msg.OpCode}, typeof({payloadType}))]");
                        sb.AppendLine($"        internal static void Handle_{methodName}(object owner, FramePacket packet, {payloadType} value)");
                        sb.AppendLine("        {");
                        sb.AppendLine("            var handled = false;");
                        if (backendGenerator != null)
                        {
                            backendGenerator.AppendGlueInvocation(sb, def, msg, backendClassName, methodName, payloadType, indent: 8);
                        }
                        sb.AppendLine("        }");
                        sb.AppendLine();
                        break;

                    case ProtocolDefinition.ChannelKind.SnapshotPipelineStage:
                        sb.AppendLine($"        [SnapshotPipelineStage(\"{EscapeString(def.RegistryId)}\", {msg.OpCode}, {msg.PipelineOrder}, typeof({payloadType}))]");
                        sb.AppendLine($"        internal static void Stage_{methodName}(object owner, FramePacket packet, {payloadType} value)");
                        sb.AppendLine("        {");
                        sb.AppendLine("            var handled = false;");
                        if (backendGenerator != null)
                        {
                            backendGenerator.AppendGlueInvocation(sb, def, msg, backendClassName, methodName, payloadType, indent: 8);
                        }
                        sb.AppendLine("        }");
                        sb.AppendLine();
                        break;
                }
            }
            sb.AppendLine("    }");

            foreach (var backend in usedBackends)
            {
                if (!CodecBackendGenerators.TryGet(backend, out var backendGenerator)) continue;

                var backendClassName = GetBackendClassName(def.RegistryId, backend);
                sb.AppendLine();
                sb.AppendLine($"    internal static partial class {backendClassName}");
                sb.AppendLine("    {");

                foreach (var msg in def.Messages)
                {
                    if (msg == null) continue;
                    if (msg.Backend != backend) continue;
                    if (string.IsNullOrWhiteSpace(msg.Name)) continue;
                    if (string.IsNullOrWhiteSpace(msg.PayloadTypeName)) continue;

                    var methodName = SanitizeIdentifier(msg.Name);
                    var payloadType = msg.PayloadTypeName.Trim();
                    backendGenerator.AppendPartialDeclarations(sb, def, msg, backendClassName, methodName, payloadType, indent: 4);
                }

                sb.AppendLine("    }");
            }

            sb.AppendLine("}");

            var filePath = Path.Combine(outputFolder, fileName);
            File.WriteAllText(filePath, sb.ToString(), Encoding.UTF8);

            AssetDatabase.Refresh();
            Debug.Log($"Generated: {filePath}");
        }

        public static void GenerateCodecBackendStubs(ProtocolDefinition def, string outputFolder, string @namespace)
        {
            if (def == null) throw new ArgumentNullException(nameof(def));
            if (string.IsNullOrWhiteSpace(outputFolder)) throw new ArgumentException("Output folder is required", nameof(outputFolder));
            if (string.IsNullOrWhiteSpace(@namespace)) throw new ArgumentException("Namespace is required", nameof(@namespace));

            var usedBackends = new HashSet<ProtocolDefinition.CodecBackend>();
            foreach (var msg in def.Messages)
            {
                if (msg == null) continue;
                usedBackends.Add(msg.Backend);
            }

            foreach (var backend in usedBackends)
            {
                if (!CodecBackendGenerators.TryGet(backend, out var generator)) continue;
                generator.GenerateImplementationStubs(def, outputFolder, @namespace);
            }
        }

        private static string GetBackendClassName(string registryId, ProtocolDefinition.CodecBackend backend)
        {
            var id = SanitizeIdentifier(registryId);
            return backend switch
            {
                ProtocolDefinition.CodecBackend.CustomBinary => $"SnapshotCustomBinary_{id}",
                ProtocolDefinition.CodecBackend.Protobuf => $"SnapshotProtobuf_{id}",
                ProtocolDefinition.CodecBackend.Json => $"SnapshotJson_{id}",
                _ => $"SnapshotCodec_{id}",
            };
        }

        public static void GenerateOpCodes(ProtocolDefinition def, string outputFolder, string @namespace)
        {
            if (def == null) throw new ArgumentNullException(nameof(def));
            if (string.IsNullOrWhiteSpace(outputFolder)) throw new ArgumentException("Output folder is required", nameof(outputFolder));
            if (string.IsNullOrWhiteSpace(@namespace)) throw new ArgumentException("Namespace is required", nameof(@namespace));

            Directory.CreateDirectory(outputFolder);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using AbilityKit.Protocol;");
            sb.AppendLine();
            sb.AppendLine($"namespace {@namespace}");
            sb.AppendLine("{");
            sb.AppendLine("    public static class OpCodes");
            sb.AppendLine("    {");

            foreach (var msg in def.Messages)
            {
                if (msg == null) continue;
                if (string.IsNullOrWhiteSpace(msg.Name)) continue;
                sb.AppendLine($"        public const int {SanitizeIdentifier(msg.Name)} = {msg.OpCode};");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            var filePath = Path.Combine(outputFolder, "OpCodes.g.cs");
            File.WriteAllText(filePath, sb.ToString(), Encoding.UTF8);

            AssetDatabase.Refresh();
            Debug.Log($"Generated: {filePath}");
        }

        /// <summary>
        /// 生成带 ProtocolOpCodeAttribute 的协议类型定义
        /// </summary>
        public static void GenerateProtocolTypesWithAttributes(ProtocolDefinition def, string outputFolder, string @namespace)
        {
            if (def == null) throw new ArgumentNullException(nameof(def));
            if (string.IsNullOrWhiteSpace(outputFolder)) throw new ArgumentException("Output folder is required", nameof(outputFolder));
            if (string.IsNullOrWhiteSpace(@namespace)) throw new ArgumentException("Namespace is required", nameof(@namespace));

            Directory.CreateDirectory(outputFolder);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System;");
            sb.AppendLine("using AbilityKit.Protocol;");
            sb.AppendLine("using MemoryPack;");
            sb.AppendLine();
            sb.AppendLine($"namespace {@namespace}");
            sb.AppendLine("{");

            foreach (var msg in def.Messages)
            {
                if (msg == null) continue;
                if (string.IsNullOrWhiteSpace(msg.Name)) continue;
                if (string.IsNullOrWhiteSpace(msg.PayloadTypeName)) continue;

                var direction = GetProtocolDirection(msg.Channel);
                var typeName = msg.PayloadTypeName.Trim();

                // 生成带 Attribute 的结构体声明
                sb.AppendLine($"    /// <summary>");
                sb.AppendLine($"    /// {msg.Name} - {GetChannelDescription(msg.Channel)}");
                sb.AppendLine($"    /// </summary>");
                sb.AppendLine($"    [ProtocolOpCode({msg.OpCode}, ProtocolDirection.{direction}, \"{EscapeString(msg.Name)}\")]");
                sb.AppendLine($"    [MemoryPackable]");
                sb.AppendLine($"    public readonly partial struct {typeName}");
                sb.AppendLine("    {");
                sb.AppendLine("        // Add your fields here");
                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("}");

            var filePath = Path.Combine(outputFolder, $"WireProtocolTypes.{SanitizeIdentifier(def.RegistryId)}.g.cs");
            File.WriteAllText(filePath, sb.ToString(), Encoding.UTF8);

            AssetDatabase.Refresh();
            Debug.Log($"Generated: {filePath}");
        }

        private static string GetProtocolDirection(ProtocolDefinition.ChannelKind channel)
        {
            return channel switch
            {
                ProtocolDefinition.ChannelKind.SnapshotDecoder => "ServerToClient",
                ProtocolDefinition.ChannelKind.SnapshotCmdHandler => "ClientToServer",
                ProtocolDefinition.ChannelKind.SnapshotPipelineStage => "Bidirectional",
                _ => "Bidirectional"
            };
        }

        private static string GetChannelDescription(ProtocolDefinition.ChannelKind channel)
        {
            return channel switch
            {
                ProtocolDefinition.ChannelKind.SnapshotDecoder => "服务器推送 - 快照数据",
                ProtocolDefinition.ChannelKind.SnapshotCmdHandler => "客户端请求 - 命令处理",
                ProtocolDefinition.ChannelKind.SnapshotPipelineStage => "双向协议 - 管道阶段",
                _ => "未知协议"
            };
        }

        private static string EscapeString(string value)
        {
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private static string SanitizeIdentifier(string name)
        {
            var sb = new StringBuilder(name.Length);
            for (var i = 0; i < name.Length; i++)
            {
                var ch = name[i];
                if (char.IsLetterOrDigit(ch) || ch == '_')
                {
                    sb.Append(ch);
                }
            }

            var result = sb.ToString();
            if (string.IsNullOrEmpty(result)) return "Msg";
            if (char.IsDigit(result[0])) return "Msg_" + result;
            return result;
        }
    }
}
